version: "3.9"

services:
  frontend:
    build: .
    container_name: bus-tour-frontend
    image: your-react-app  # build するならこれは不要でもOK
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bus-tour.rule=Host(`test01.detascent.com`)"
      - "traefik.http.routers.bus-tour.entrypoints=websecure"
      - "traefik.http.routers.bus-tour.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.bus-tour.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$2y$05$0psW/YylYHsjbX9qQXrGYOpHduerqHw5wHl8H5rVX29n9wiEOuFF6"
    networks:
      - traefik-net

  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lets-encrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.lets-encrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.lets-encrypt.acme.email=b182587@outlook.com"
      - "--certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge

volumes:
  letsencrypt: