version: "3.9"

services:
  frontend:
    build: .
    container_name: bus-tour-frontend
    image: your-react-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bus-tour.rule=Host(`test01.detascent.com`)"
      - "traefik.http.routers.bus-tour.entrypoints=websecure"
      - "traefik.http.routers.bus-tour.tls.certresolver=myresolver"
      - "traefik.http.routers.bus-tour.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$2y$05$0psW/YylYHsjbX9qQXrGYOpHduerqHw5wHl8H5rVX29n9wiEOuFF6"
    networks:
      - traefik-net

  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.myresolver.acme.email=your@email.com"
      - "--certificatesResolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge

volumes:
  letsencrypt:
